/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;
import Modelo.Carton;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
/**
 *
 * @author Joan
 */
public class CartonPanel extends javax.swing.JPanel {
private Carton carton;
private JLabel[][] lblNumeros;
    /**
     * Creates new form PanelCarton
     */
    public CartonPanel() {
        initComponents();
    }
public void inicializarCarton(Carton carton) {
    this.carton = carton;
    this.lblNumeros = new JLabel[5][5];
    
    lblNumeros[0][0] = lbl00; lblNumeros[0][1] = lbl05; lblNumeros[0][2] = lbl10; lblNumeros[0][3] = lbl15; lblNumeros[0][4] = lbl20;
lblNumeros[1][0] = lbl01; lblNumeros[1][1] = lbl06; lblNumeros[1][2] = lbl11; lblNumeros[1][3] = lbl16; lblNumeros[1][4] = lbl21;
lblNumeros[2][0] = lbl02; lblNumeros[2][1] = lbl07; lblNumeros[2][2] = lbl12; lblNumeros[2][3] = lbl17; lblNumeros[2][4] = lbl22;
lblNumeros[3][0] = lbl03; lblNumeros[3][1] = lbl08; lblNumeros[3][2] = lbl13; lblNumeros[3][3] = lbl18; lblNumeros[3][4] = lbl23;
lblNumeros[4][0] = lbl04; lblNumeros[4][1] = lbl09; lblNumeros[4][2] = lbl14; lblNumeros[4][3] = lbl19; lblNumeros[4][4] = lbl24;
    
    cargarNumeros();
    lblIdCarton.setText(carton.getId());
}

private void cargarNumeros() {
    int[][] numeros = carton.getNumeros();
    boolean[][] marcados = carton.getMarcados();
    
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            JLabel lbl = lblNumeros[i][j];
            
            if (i == 2 && j == 2) {
                lbl.setText("LIBRE");
                lbl.setBackground(new Color(255, 235, 59));
            } else {
                lbl.setText(String.valueOf(numeros[i][j]));
            }
            
            lbl.setOpaque(true);
            lbl.setHorizontalAlignment(JLabel.CENTER);
            lbl.setFont(new Font("Arial", Font.BOLD, 18));
            lbl.setBorder(BorderFactory.createLineBorder(Color.BLACK, 2));
            
            if (marcados[i][j]) {
                lbl.setBackground(new Color(76, 175, 80));
                lbl.setForeground(Color.WHITE);
            } else {
                lbl.setBackground(Color.WHITE);
                lbl.setForeground(Color.BLACK);
            }
        }
    }
}

public void actualizarMarcas() {
    boolean[][] marcados = carton.getMarcados();
    
    for (int i = 0; i < 5; i++) {
        for (int j = 0; j < 5; j++) {
            if (marcados[i][j]) {
                lblNumeros[i][j].setBackground(new Color(76, 175, 80));
                lblNumeros[i][j].setForeground(Color.WHITE);
            } else if (i == 2 && j == 2) {
                lblNumeros[i][j].setBackground(new Color(255, 235, 59));
            } else {
                lblNumeros[i][j].setBackground(Color.WHITE);
                lblNumeros[i][j].setForeground(Color.BLACK);
            }
        }
    }
}

public void resaltarGanador() {
    setBorder(BorderFactory.createLineBorder(Color.RED, 5));
}

public Carton getCarton() {
    return carton;
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIdCarton = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblB = new javax.swing.JLabel();
        lblI = new javax.swing.JLabel();
        lblN = new javax.swing.JLabel();
        lblG = new javax.swing.JLabel();
        lblO = new javax.swing.JLabel();
        lbl00 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        lblIdCarton.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblIdCarton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblIdCarton.setText("Carton-1");
        add(lblIdCarton, java.awt.BorderLayout.PAGE_START);

        lblB.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblB.setText("B");

        lblI.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblI.setText("I");

        lblN.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblN.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblN.setText("N");

        lblG.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblG.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblG.setText("G");

        lblO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblO.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblO.setText("O");

        lbl00.setText("jLabel2");

        lbl01.setText("jLabel3");

        lbl02.setText("jLabel4");

        lbl03.setText("jLabel5");

        lbl04.setText("jLabel6");

        lbl05.setText("jLabel7");

        lbl06.setText("jLabel8");

        lbl07.setText("jLabel9");

        lbl08.setText("jLabel10");

        lbl09.setText("jLabel11");

        lbl10.setText("jLabel12");

        lbl11.setText("jLabel13");

        lbl12.setText("jLabel14");

        lbl13.setText("jLabel15");

        lbl14.setText("jLabel16");

        lbl16.setText("jLabel17");

        lbl17.setText("jLabel18");

        lbl18.setText("jLabel19");

        lbl19.setText("jLabel20");

        lbl20.setText("jLabel21");

        lbl21.setText("jLabel22");

        lbl22.setText("jLabel23");

        lbl23.setText("jLabel24");

        lbl24.setText("jLabel25");

        lbl15.setText("jLabel26");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl06)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl07))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl00)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl01))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl19)
                                    .addComponent(lbl15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl20)
                                    .addComponent(lbl13))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(lblI, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(lblN, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbl16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl02)
                                    .addComponent(lbl08)
                                    .addComponent(lbl14)
                                    .addComponent(lbl21))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(75, 75, 75)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbl09)
                                            .addComponent(lbl03)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lbl22)))))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lblO, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                                .addComponent(lbl24))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl18))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbl10)
                                    .addComponent(lbl04))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl05)
                                    .addComponent(lbl11))))
                        .addGap(64, 64, 64))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(lbl12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblB, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblI, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblG, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblO, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl00)
                    .addComponent(lbl01)
                    .addComponent(lbl02)
                    .addComponent(lbl03)
                    .addComponent(lbl04)
                    .addComponent(lbl05))
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl06)
                    .addComponent(lbl07)
                    .addComponent(lbl08)
                    .addComponent(lbl09)
                    .addComponent(lbl10)
                    .addComponent(lbl11))
                .addGap(18, 18, 18)
                .addComponent(lbl12)
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl13)
                    .addComponent(lbl14)
                    .addComponent(lbl16)
                    .addComponent(lbl17)
                    .addComponent(lbl18)
                    .addComponent(lbl15))
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl19)
                    .addComponent(lbl20)
                    .addComponent(lbl21)
                    .addComponent(lbl22)
                    .addComponent(lbl23)
                    .addComponent(lbl24))
                .addContainerGap(117, Short.MAX_VALUE))
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lblB;
    private javax.swing.JLabel lblG;
    private javax.swing.JLabel lblI;
    private javax.swing.JLabel lblIdCarton;
    private javax.swing.JLabel lblN;
    private javax.swing.JLabel lblO;
    // End of variables declaration//GEN-END:variables
}
