/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;
import java.awt.BorderLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author Joan
 */
public class MainFrame extends javax.swing.JFrame {
private PanelFondoImagen panelFondo;
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
     String rutaImagen = "/Vista/resources/Imagen de WhatsApp 2025-11-08 a las 20.24.21_dc25733f.jpg";
        panelFondo = new PanelFondoImagen(rutaImagen);
        panelFondo.setLayout(new BorderLayout());
        this.setContentPane(panelFondo);
        
        
        // --- 2. ARREGLO PARA EL NORTE (TÍTULO Y BOTONES) ---
        // Creamos un panel "contenedor" para apilarlos
        
        JPanel panelNorteContenedor = new JPanel();
        // BoxLayout (Y_AXIS) apila los componentes verticalmente
        panelNorteContenedor.setLayout(new BoxLayout(panelNorteContenedor, BoxLayout.Y_AXIS));
        panelNorteContenedor.setOpaque(false); // ¡Hacerlo transparente!
        
        // Agregamos tus paneles al contenedor (los que NetBeans creó)
        panelNorteContenedor.add(this.jPanel1); // El del título
        panelNorteContenedor.add(this.jPanel2); // El de los botones
        
        
        // --- 3. RE-AGREGA TODO AL FONDO (USANDO LOS NOMBRES CORRECTOS) ---
        
        // Agrega el contenedor (con el título y botones) al NORTE
        panelFondo.add(panelNorteContenedor, BorderLayout.NORTH);
        
        // Agrega tu JScrollPane (jScrollPane2) al CENTRO
        panelFondo.add(this.jScrollPane2, BorderLayout.CENTER);
        
        // Agrega la etiqueta al SUR (abajo)
        panelFondo.add(this.lblUltimoNumero, BorderLayout.SOUTH);
        
        
      
        this.jPanel1.setOpaque(false);
        this.jPanel2.setOpaque(false);
        
        // Tu etiqueta de abajo
        this.lblUltimoNumero.setOpaque(false);

       
        this.jScrollPane2.setOpaque(false);
        
        // 2. Hace transparente el "visor" del scroll
        this.jScrollPane2.getViewport().setOpaque(false);
        
        // 3. Hace transparente TU panel (el que está adentro)
        this.panelCentral.setOpaque(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnCrearCarton = new javax.swing.JButton();
        btnSacarBola = new javax.swing.JButton();
        btnModoJuego = new javax.swing.JButton();
        btnReiniciar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        lblUltimoNumero = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        panelCentral = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnCrearCarton.setBackground(new java.awt.Color(51, 51, 51));
        btnCrearCarton.setForeground(new java.awt.Color(255, 255, 255));
        btnCrearCarton.setText("Crear Carton");
        btnCrearCarton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnCrearCarton.setFocusPainted(false);

        btnSacarBola.setBackground(new java.awt.Color(51, 51, 51));
        btnSacarBola.setForeground(new java.awt.Color(255, 255, 255));
        btnSacarBola.setText("Sacar Bola");
        btnSacarBola.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnSacarBola.setFocusPainted(false);

        btnModoJuego.setBackground(new java.awt.Color(51, 51, 51));
        btnModoJuego.setForeground(new java.awt.Color(255, 255, 255));
        btnModoJuego.setText("Modo:Normal");
        btnModoJuego.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnModoJuego.setFocusPainted(false);

        btnReiniciar.setBackground(new java.awt.Color(51, 51, 51));
        btnReiniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnReiniciar.setText("Reiniciar");
        btnReiniciar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        btnReiniciar.setFocusPainted(false);
        btnReiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(btnCrearCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105)
                .addComponent(btnSacarBola, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 289, Short.MAX_VALUE)
                .addComponent(btnModoJuego)
                .addGap(83, 83, 83)
                .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(63, 63, 63))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearCarton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSacarBola, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReiniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(0, 0, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bingo");

        lblUltimoNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblUltimoNumero.setForeground(new java.awt.Color(255, 255, 255));
        lblUltimoNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUltimoNumero.setText("Ultimo Numero:");

        panelCentral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jScrollPane2.setViewportView(panelCentral);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jSeparator1))
                    .addComponent(lblUltimoNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 351, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblUltimoNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReiniciarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReiniciarActionPerformed
public JButton getBtnCrearCarton() { 
    return btnCrearCarton; 
}

public JButton getBtnSacarBola() { 
    return btnSacarBola; 
}

public JButton getBtnReiniciar() { 
    return btnReiniciar; 
}

public JButton getBtnModoJuego() { 
    return btnModoJuego; 
}

public JPanel getPanelCentral() { 
    return panelCentral; 
}

public JLabel getLblUltimoNumero() { 
    return lblUltimoNumero; 
}

public void actualizarUltimoNumero(int numero) {
    lblUltimoNumero.setText("Último número: " + numero);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCarton;
    private javax.swing.JButton btnModoJuego;
    private javax.swing.JButton btnReiniciar;
    private javax.swing.JButton btnSacarBola;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblUltimoNumero;
    private javax.swing.JPanel panelCentral;
    // End of variables declaration//GEN-END:variables
}
