/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Tombola;
import java.awt.*;
import javax.swing.*;

/**
 *
 * @author itsth
 */
public class PanelTombola extends javax.swing.JPanel {

    private Tombola tombola;

    /**
     * Creates new form PanelTombola
     */
    public PanelTombola() {
        initComponents();

    }

    public void configurarEventosConFacade(Runnable onNumeroSacado, Runnable onNumeroIngresado) {
        btnSacarBola.addActionListener(e -> {
            int numero = tombola.sacarBola();
            if (numero == -1) {
                JOptionPane.showMessageDialog(this,
                        "No quedan más bolas disponibles",
                        "Tombola Completa",
                        JOptionPane.INFORMATION_MESSAGE);
            } else {
                actualizarInterfaz();
                onNumeroSacado.run();
            }
        });

        txtManual.addActionListener(e -> btnIngresar.doClick());
    }

    public void reiniciar() {
        actualizarInterfaz();
    }

    public void setTombola(Tombola tombola) {
        this.tombola = tombola;
        actualizarInterfaz();
    }

    public void actualizarInterfaz() {
        int ultimo = tombola.getUltimoNumeroCantado();
        lblNumeroActual.setText(ultimo == 0 ? "--" : String.valueOf(ultimo));

        int cantados = 75 - contarRestantes();
        lblRestantes.setText("Restantes: " + contarRestantes());
        lblCantados.setText("Cantados: " + cantados);
    }

    private int contarRestantes() {
        return tombola.getBolasDisponibles().size();
    }


    public JTextField getTxtManual() {
        return txtManual;
    }

    public JButton getBtnIngresar() {
        return btnIngresar;
    }
    
    public JComboBox<String> getCmbModoJuego() {
        return cmbModoJuego;
    }

    public void configurarModoAutomatico() {
        btnSacarBola.setEnabled(true);
        txtManual.setEnabled(false);
        btnIngresar.setEnabled(false);
    }

    public void configurarModoManual() {
        btnSacarBola.setEnabled(false);
        txtManual.setEnabled(true);
        btnIngresar.setEnabled(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblRestantes = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblCantados = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        lblNumeroActual = new javax.swing.JLabel();
        txtManual = new javax.swing.JTextField();
        btnIngresar = new javax.swing.JButton();
        lblNumeroCantado = new javax.swing.JLabel();
        lblModoJuego = new javax.swing.JLabel();
        cmbModoJuego = new javax.swing.JComboBox<>();
        btnSacarBola = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 0, 51));

        jLabel2.setBackground(new java.awt.Color(255, 0, 51));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("TÓMBOLA");
        jPanel1.add(jLabel2);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new java.awt.GridLayout(1, 0));

        lblRestantes.setBackground(new java.awt.Color(102, 204, 255));
        lblRestantes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRestantes.setForeground(new java.awt.Color(255, 255, 255));
        lblRestantes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestantes.setText("Restantes: 75");
        lblRestantes.setOpaque(true);
        jPanel3.add(lblRestantes);

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        lblCantados.setBackground(new java.awt.Color(153, 153, 153));
        lblCantados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblCantados.setForeground(new java.awt.Color(255, 255, 255));
        lblCantados.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCantados.setText("Cantados: 0");
        lblCantados.setOpaque(true);
        jPanel4.add(lblCantados);

        jPanel3.add(jPanel4);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        lblNumeroActual.setBackground(new java.awt.Color(51, 51, 51));
        lblNumeroActual.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        lblNumeroActual.setForeground(new java.awt.Color(255, 153, 0));
        lblNumeroActual.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumeroActual.setText("--");
        lblNumeroActual.setOpaque(true);

        btnIngresar.setBackground(new java.awt.Color(0, 102, 255));
        btnIngresar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnIngresar.setForeground(new java.awt.Color(255, 255, 255));
        btnIngresar.setText("INGRESAR");

        lblNumeroCantado.setText("Numero Cantado:");

        lblModoJuego.setText("Modo de Juego:");

        cmbModoJuego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Automatico", "Manual" }));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblNumeroActual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumeroCantado, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtManual, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(btnIngresar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(cmbModoJuego, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModoJuego)
                    .addComponent(cmbModoJuego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroCantado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtManual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1)))
                .addComponent(lblNumeroActual, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.add(jPanel5, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.PAGE_END);

        btnSacarBola.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSacarBola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vista/Resources/67-number-3d-ball-red.png"))); // NOI18N
        btnSacarBola.setText("SACAR BOLA");
        add(btnSacarBola, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JButton btnSacarBola;
    private javax.swing.JComboBox<String> cmbModoJuego;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCantados;
    private javax.swing.JLabel lblModoJuego;
    private javax.swing.JLabel lblNumeroActual;
    private javax.swing.JLabel lblNumeroCantado;
    private javax.swing.JLabel lblRestantes;
    private javax.swing.JTextField txtManual;
    // End of variables declaration//GEN-END:variables
}
