/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Vista;

import Modelo.Tablero;
import java.awt.Color;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.JLabel;

/**
 *
 * @author oscar
 */
public class TableroPanel extends javax.swing.JPanel {
    private Tablero tablero;
    private JLabel[] lblNumeros;
    /**
     * Creates new form TableroPanel
     */
    public TableroPanel() {
        initComponents();
        inicializarTablero();
    }
    
   private void inicializarTablero() {
    lblNumeros = new JLabel[75];
    
     lblNumeros[0] = lbl00;
    lblNumeros[1] = lbl01;
    lblNumeros[2] = lbl02;
    lblNumeros[3] = lbl03;
    lblNumeros[4] = lbl04;
    lblNumeros[5] = lbl05;
    lblNumeros[6] = lbl06;
    lblNumeros[7] = lbl07;
    lblNumeros[8] = lbl08;
    lblNumeros[9] = lbl09;
    lblNumeros[10] = lbl10;
    lblNumeros[11] = lbl11;
    lblNumeros[12] = lbl12;
    lblNumeros[13] = lbl13;
    lblNumeros[14] = lbl14;
    lblNumeros[15] = lbl15;
    lblNumeros[16] = lbl16;
    lblNumeros[17] = lbl17;
    lblNumeros[18] = lbl18;
    lblNumeros[19] = lbl19;
    lblNumeros[20] = lbl20;
    lblNumeros[21] = lbl21;
    lblNumeros[22] = lbl22;
    lblNumeros[23] = lbl23;
    lblNumeros[24] = lbl24;
    lblNumeros[25] = lbl25;
    lblNumeros[26] = lbl26;
    lblNumeros[27] = lbl27;
    lblNumeros[28] = lbl28;
    lblNumeros[29] = lbl29;
    lblNumeros[30] = lbl30;
    lblNumeros[31] = lbl31;
    lblNumeros[32] = lbl32;
    lblNumeros[33] = lbl33;
    lblNumeros[34] = lbl34;
    lblNumeros[35] = lbl35;
    lblNumeros[36] = lbl36;
    lblNumeros[37] = lbl37;
    lblNumeros[38] = lbl38;
    lblNumeros[39] = lbl39;
    lblNumeros[40] = lbl40;
    lblNumeros[41] = lbl41;
    lblNumeros[42] = lbl42;
    lblNumeros[43] = lbl43;
    lblNumeros[44] = lbl44;
    lblNumeros[45] = lbl45;
    lblNumeros[46] = lbl46;
    lblNumeros[47] = lbl47;
    lblNumeros[48] = lbl48;
    lblNumeros[49] = lbl49;
    lblNumeros[50] = lbl50;
    lblNumeros[51] = lbl51;
    lblNumeros[52] = lbl52;
    lblNumeros[53] = lbl53;
    lblNumeros[54] = lbl54;
    lblNumeros[55] = lbl55;
    lblNumeros[56] = lbl56;
    lblNumeros[57] = lbl57;
    lblNumeros[58] = lbl58;
    lblNumeros[59] = lbl59;
    lblNumeros[60] = lbl60;
    lblNumeros[61] = lbl61;
    lblNumeros[62] = lbl62;
    lblNumeros[63] = lbl63;
    lblNumeros[64] = lbl64;
    lblNumeros[65] = lbl65;
    lblNumeros[66] = lbl66;
    lblNumeros[67] = lbl67;
    lblNumeros[68] = lbl68;
    lblNumeros[69] = lbl69;
    lblNumeros[70] = lbl70;
    lblNumeros[71] = lbl71;
    lblNumeros[72] = lbl72;
    lblNumeros[73] = lbl73;
    lblNumeros[74] = lbl74;
    
   
for (int i = 0; i < 75; i++) {
    lblNumeros[i].setText(String.valueOf(i + 1));
    lblNumeros[i].setOpaque(true);
    lblNumeros[i].setBackground(Color.WHITE);
    lblNumeros[i].setForeground(Color.BLACK);
    lblNumeros[i].setHorizontalAlignment(JLabel.CENTER);
    lblNumeros[i].setVerticalAlignment(JLabel.CENTER);
    lblNumeros[i].setFont(new Font("Arial", Font.BOLD, 16)); 
    
    lblNumeros[i].setBorder(BorderFactory.createLineBorder(new Color(50, 50, 50), 2));
    
    
    lblNumeros[i].setPreferredSize(new java.awt.Dimension(45, 45));
    lblNumeros[i].setMinimumSize(new java.awt.Dimension(45, 45));   
    lblNumeros[i].setMaximumSize(new java.awt.Dimension(45, 45));  
  }
}

public void marcarNumero(int numero) {
    if (numero >= 1 && numero <= 75) {
        lblNumeros[numero - 1].setBackground(new Color(76, 175, 80));
        lblNumeros[numero - 1].setForeground(Color.WHITE);
    }
}

public void desmarcarNumero(int numero) {
    if (numero >= 1 && numero <= 75) {
        lblNumeros[numero - 1].setBackground(Color.WHITE);
        lblNumeros[numero - 1].setForeground(Color.BLACK);
    }
}

public void reiniciar() {
    for (int i = 0; i < 75; i++) {
        lblNumeros[i].setBackground(Color.WHITE);
        lblNumeros[i].setForeground(Color.BLACK);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl59 = new javax.swing.JLabel();
        lbl60 = new javax.swing.JLabel();
        lbl61 = new javax.swing.JLabel();
        lbl62 = new javax.swing.JLabel();
        lbl19 = new javax.swing.JLabel();
        lbl63 = new javax.swing.JLabel();
        lbl20 = new javax.swing.JLabel();
        lbl64 = new javax.swing.JLabel();
        lbl21 = new javax.swing.JLabel();
        lbl65 = new javax.swing.JLabel();
        lbl22 = new javax.swing.JLabel();
        lbl66 = new javax.swing.JLabel();
        lbl23 = new javax.swing.JLabel();
        lbl67 = new javax.swing.JLabel();
        lbl24 = new javax.swing.JLabel();
        lbl68 = new javax.swing.JLabel();
        lbl25 = new javax.swing.JLabel();
        lbl26 = new javax.swing.JLabel();
        lbl27 = new javax.swing.JLabel();
        lbl28 = new javax.swing.JLabel();
        lbl69 = new javax.swing.JLabel();
        lbl70 = new javax.swing.JLabel();
        lbl71 = new javax.swing.JLabel();
        lbl72 = new javax.swing.JLabel();
        lbl29 = new javax.swing.JLabel();
        lbl73 = new javax.swing.JLabel();
        lbl30 = new javax.swing.JLabel();
        lbl74 = new javax.swing.JLabel();
        lbl31 = new javax.swing.JLabel();
        lbl32 = new javax.swing.JLabel();
        lbl33 = new javax.swing.JLabel();
        lbl34 = new javax.swing.JLabel();
        lbl35 = new javax.swing.JLabel();
        lbl36 = new javax.swing.JLabel();
        lbl37 = new javax.swing.JLabel();
        lbl38 = new javax.swing.JLabel();
        lbl00 = new javax.swing.JLabel();
        lbl01 = new javax.swing.JLabel();
        lbl02 = new javax.swing.JLabel();
        lbl03 = new javax.swing.JLabel();
        lbl04 = new javax.swing.JLabel();
        lbl05 = new javax.swing.JLabel();
        lbl06 = new javax.swing.JLabel();
        lbl39 = new javax.swing.JLabel();
        lbl07 = new javax.swing.JLabel();
        lbl40 = new javax.swing.JLabel();
        lbl08 = new javax.swing.JLabel();
        lbl41 = new javax.swing.JLabel();
        lbl42 = new javax.swing.JLabel();
        lbl43 = new javax.swing.JLabel();
        lbl44 = new javax.swing.JLabel();
        lbl45 = new javax.swing.JLabel();
        lbl46 = new javax.swing.JLabel();
        lbl47 = new javax.swing.JLabel();
        lbl48 = new javax.swing.JLabel();
        lbl49 = new javax.swing.JLabel();
        lbl50 = new javax.swing.JLabel();
        lbl51 = new javax.swing.JLabel();
        lbl52 = new javax.swing.JLabel();
        lbl09 = new javax.swing.JLabel();
        lbl53 = new javax.swing.JLabel();
        lbl10 = new javax.swing.JLabel();
        lbl54 = new javax.swing.JLabel();
        lbl11 = new javax.swing.JLabel();
        lbl55 = new javax.swing.JLabel();
        lbl12 = new javax.swing.JLabel();
        lbl56 = new javax.swing.JLabel();
        lbl13 = new javax.swing.JLabel();
        lbl57 = new javax.swing.JLabel();
        lbl14 = new javax.swing.JLabel();
        lbl58 = new javax.swing.JLabel();
        lbl15 = new javax.swing.JLabel();
        lbl16 = new javax.swing.JLabel();
        lbl17 = new javax.swing.JLabel();
        lbl18 = new javax.swing.JLabel();

        lbl59.setText("jLabel60");

        lbl60.setText("jLabel61");

        lbl61.setText("jLabel62");

        lbl62.setText("jLabel63");

        lbl19.setText("jLabel20");

        lbl63.setText("jLabel64");

        lbl20.setText("jLabel21");

        lbl64.setText("jLabel65");

        lbl21.setText("jLabel22");

        lbl65.setText("jLabel66");

        lbl22.setText("jLabel23");

        lbl66.setText("jLabel67");

        lbl23.setText("jLabel24");

        lbl67.setText("jLabel68");

        lbl24.setText("jLabel25");

        lbl68.setText("jLabel69");

        lbl25.setText("jLabel26");

        lbl26.setText("jLabel27");

        lbl27.setText("jLabel28");

        lbl28.setText("jLabel29");

        lbl69.setText("jLabel70");

        lbl70.setText("jLabel71");

        lbl71.setText("jLabel72");

        lbl72.setText("jLabel73");

        lbl29.setText("jLabel30");

        lbl73.setText("jLabel74");

        lbl30.setText("jLabel31");

        lbl74.setText("jLabel75");

        lbl31.setText("jLabel32");

        lbl32.setText("jLabel33");

        lbl33.setText("jLabel34");

        lbl34.setText("jLabel35");

        lbl35.setText("jLabel36");

        lbl36.setText("jLabel37");

        lbl37.setText("jLabel38");

        lbl38.setText("jLabel39");

        lbl00.setText("jLabel1");

        lbl01.setText("jLabel2");

        lbl02.setText("jLabel3");

        lbl03.setText("jLabel4");

        lbl04.setText("jLabel5");

        lbl05.setText("jLabel6");

        lbl06.setText("jLabel7");

        lbl39.setText("jLabel40");

        lbl07.setText("jLabel8");

        lbl40.setText("jLabel41");

        lbl08.setText("jLabel9");

        lbl41.setText("jLabel42");

        lbl42.setText("jLabel43");

        lbl43.setText("jLabel44");

        lbl44.setText("jLabel45");

        lbl45.setText("jLabel46");

        lbl46.setText("jLabel47");

        lbl47.setText("jLabel48");

        lbl48.setText("jLabel49");

        lbl49.setText("jLabel50");

        lbl50.setText("jLabel51");

        lbl51.setText("jLabel52");

        lbl52.setText("jLabel53");

        lbl09.setText("jLabel10");

        lbl53.setText("jLabel54");

        lbl10.setText("jLabel11");

        lbl54.setText("jLabel55");

        lbl11.setText("jLabel12");

        lbl55.setText("jLabel56");

        lbl12.setText("jLabel13");

        lbl56.setText("jLabel57");

        lbl13.setText("jLabel14");

        lbl57.setText("jLabel58");

        lbl14.setText("jLabel15");

        lbl58.setText("jLabel59");

        lbl15.setText("jLabel16");

        lbl16.setText("jLabel17");

        lbl17.setText("jLabel18");

        lbl18.setText("jLabel19");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl60, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(lbl45, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl30, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl15, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl00, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(lbl61, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(13, 13, 13)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lbl01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lbl16, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(lbl31, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(lbl46, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl17, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl32, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl47, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl62, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl18, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl33, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl48, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl63, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl19, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl34, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl49, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl64, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl20, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl35, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl50, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl65, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbl06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl21, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl36, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl51, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl66, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbl07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lbl22, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(lbl37, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addComponent(lbl52, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                    .addComponent(lbl67))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lbl68, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl53, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl08, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbl23, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(lbl38, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbl09, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbl24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl14))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbl25)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl26)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl27)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl28)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbl29))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl39)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl40)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl41)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl42)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl43)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl44))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl69, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl54, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(lbl55)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl56)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl57)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl58)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl59))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lbl70)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl71)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl72)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl73)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbl74)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl00)
                    .addComponent(lbl01)
                    .addComponent(lbl02)
                    .addComponent(lbl03)
                    .addComponent(lbl04)
                    .addComponent(lbl05)
                    .addComponent(lbl06)
                    .addComponent(lbl07)
                    .addComponent(lbl08)
                    .addComponent(lbl09)
                    .addComponent(lbl10)
                    .addComponent(lbl11)
                    .addComponent(lbl12)
                    .addComponent(lbl13)
                    .addComponent(lbl14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl15)
                    .addComponent(lbl16)
                    .addComponent(lbl17)
                    .addComponent(lbl18)
                    .addComponent(lbl19)
                    .addComponent(lbl20)
                    .addComponent(lbl21)
                    .addComponent(lbl22)
                    .addComponent(lbl23)
                    .addComponent(lbl24)
                    .addComponent(lbl25)
                    .addComponent(lbl26)
                    .addComponent(lbl27)
                    .addComponent(lbl28)
                    .addComponent(lbl29))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl30)
                    .addComponent(lbl31)
                    .addComponent(lbl32)
                    .addComponent(lbl33)
                    .addComponent(lbl34)
                    .addComponent(lbl35)
                    .addComponent(lbl36)
                    .addComponent(lbl37)
                    .addComponent(lbl38)
                    .addComponent(lbl39)
                    .addComponent(lbl40)
                    .addComponent(lbl41)
                    .addComponent(lbl42)
                    .addComponent(lbl43)
                    .addComponent(lbl44))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl45)
                    .addComponent(lbl46)
                    .addComponent(lbl47)
                    .addComponent(lbl48)
                    .addComponent(lbl49)
                    .addComponent(lbl50)
                    .addComponent(lbl51)
                    .addComponent(lbl52)
                    .addComponent(lbl53)
                    .addComponent(lbl54)
                    .addComponent(lbl55)
                    .addComponent(lbl56)
                    .addComponent(lbl57)
                    .addComponent(lbl58)
                    .addComponent(lbl59))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl61)
                        .addComponent(lbl62)
                        .addComponent(lbl63)
                        .addComponent(lbl64)
                        .addComponent(lbl65)
                        .addComponent(lbl66)
                        .addComponent(lbl67)
                        .addComponent(lbl70)
                        .addComponent(lbl71)
                        .addComponent(lbl68)
                        .addComponent(lbl69)
                        .addComponent(lbl72)
                        .addComponent(lbl73)
                        .addComponent(lbl74))
                    .addComponent(lbl60))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl00;
    private javax.swing.JLabel lbl01;
    private javax.swing.JLabel lbl02;
    private javax.swing.JLabel lbl03;
    private javax.swing.JLabel lbl04;
    private javax.swing.JLabel lbl05;
    private javax.swing.JLabel lbl06;
    private javax.swing.JLabel lbl07;
    private javax.swing.JLabel lbl08;
    private javax.swing.JLabel lbl09;
    private javax.swing.JLabel lbl10;
    private javax.swing.JLabel lbl11;
    private javax.swing.JLabel lbl12;
    private javax.swing.JLabel lbl13;
    private javax.swing.JLabel lbl14;
    private javax.swing.JLabel lbl15;
    private javax.swing.JLabel lbl16;
    private javax.swing.JLabel lbl17;
    private javax.swing.JLabel lbl18;
    private javax.swing.JLabel lbl19;
    private javax.swing.JLabel lbl20;
    private javax.swing.JLabel lbl21;
    private javax.swing.JLabel lbl22;
    private javax.swing.JLabel lbl23;
    private javax.swing.JLabel lbl24;
    private javax.swing.JLabel lbl25;
    private javax.swing.JLabel lbl26;
    private javax.swing.JLabel lbl27;
    private javax.swing.JLabel lbl28;
    private javax.swing.JLabel lbl29;
    private javax.swing.JLabel lbl30;
    private javax.swing.JLabel lbl31;
    private javax.swing.JLabel lbl32;
    private javax.swing.JLabel lbl33;
    private javax.swing.JLabel lbl34;
    private javax.swing.JLabel lbl35;
    private javax.swing.JLabel lbl36;
    private javax.swing.JLabel lbl37;
    private javax.swing.JLabel lbl38;
    private javax.swing.JLabel lbl39;
    private javax.swing.JLabel lbl40;
    private javax.swing.JLabel lbl41;
    private javax.swing.JLabel lbl42;
    private javax.swing.JLabel lbl43;
    private javax.swing.JLabel lbl44;
    private javax.swing.JLabel lbl45;
    private javax.swing.JLabel lbl46;
    private javax.swing.JLabel lbl47;
    private javax.swing.JLabel lbl48;
    private javax.swing.JLabel lbl49;
    private javax.swing.JLabel lbl50;
    private javax.swing.JLabel lbl51;
    private javax.swing.JLabel lbl52;
    private javax.swing.JLabel lbl53;
    private javax.swing.JLabel lbl54;
    private javax.swing.JLabel lbl55;
    private javax.swing.JLabel lbl56;
    private javax.swing.JLabel lbl57;
    private javax.swing.JLabel lbl58;
    private javax.swing.JLabel lbl59;
    private javax.swing.JLabel lbl60;
    private javax.swing.JLabel lbl61;
    private javax.swing.JLabel lbl62;
    private javax.swing.JLabel lbl63;
    private javax.swing.JLabel lbl64;
    private javax.swing.JLabel lbl65;
    private javax.swing.JLabel lbl66;
    private javax.swing.JLabel lbl67;
    private javax.swing.JLabel lbl68;
    private javax.swing.JLabel lbl69;
    private javax.swing.JLabel lbl70;
    private javax.swing.JLabel lbl71;
    private javax.swing.JLabel lbl72;
    private javax.swing.JLabel lbl73;
    private javax.swing.JLabel lbl74;
    // End of variables declaration//GEN-END:variables
}
